### ISSUE TITLE
Need to split files over 1M

### ISSUE THREAD

**Issue by afbjorklund** [afbjorklund/gradle-memcached-plugin#1]
The default maximum slab size (and thus value size) of memcached is just 1M, minus internal overhead.

So files that are over say 512K needs to be split into several pieces, if they are to be stored anywhere...

**Comment by afbjorklund** [comment]
```
2018-06-13 20:30:21.311 ERROR net.spy.memcached.protocol.ascii.StoreOperationImpl:  Error:  SERVER_ERROR object too large for cache
2018-06-13 20:30:21.312 INFO net.spy.memcached.MemcachedConnection:  Reconnection due to exception handling a memcached operation on {QA sa=/127.0.0.1:11211, #Rops=2, #Wops=0, #iq=0, topRop=Cmd: set Key: 2037e32a317174fb8024f92fa05a6d08 Flags: 2050 Exp: 0 Data Length: 1235182, topWop=null, toWrite=0, interested=1}. This may be due to an authentication failure.
OperationException: SERVER: SERVER_ERROR object too large for cache
        at net.spy.memcached.protocol.BaseOperationImpl.handleError(BaseOperationImpl.java:192)
        at net.spy.memcached.protocol.ascii.OperationImpl.readFromBuffer(OperationImpl.java:152)
        at net.spy.memcached.MemcachedConnection.readBufferAndLogMetrics(MemcachedConnection.java:872)
        at net.spy.memcached.MemcachedConnection.handleReads(MemcachedConnection.java:851)
        at net.spy.memcached.MemcachedConnection.handleReadsAndWrites(MemcachedConnection.java:732)
        at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:697)
        at net.spy.memcached.MemcachedConnection.handleIO(MemcachedConnection.java:450)
        at net.spy.memcached.MemcachedConnection.run(MemcachedConnection.java:1457)

```

**Comment by afbjorklund** [comment]
The workaround is to increase the slab size of the memcached daemon, to _above_ 1m (up to 128m).

>        -I <size>
>               Override the default size of each slab page. The default size is 1mb. Default value for this parameter is 1m, minimum is 1k, max is  128m.   Adjusting
>               this  value  changes  the  item size limit.  Beware that this also increases the number of slabs (use -v to view), and the overal memory usage of mem‐
>               cached.
>
